// MASTER NAME SERVER for PRACTICELAB.net
// maintained by: me myself alone
// CHANGELOG:
// 1. 12 March 2026 - I created this file 
//
options {
  directory "/var/named";
  // version statement - inhibited for security
  // (avoids hacking any known weaknesses)	
  version "get lost";
  // optional - disables all transfers 
  // slaves allowed in zone clauses
  allow-transfer {"none";};
  // Closed DNS - permits only local IPs to issue recursive queries 
  // remove if an Open DNS required to support all users 
  // or add additional ranges 
  allow-recursion {192.168.2.0/24;};
};
//
// log to /var/log/named/example.log all events from 
// info UP in severity (no debug)
// defaults to use 3 files in rotation
// BIND 8.x logging MUST COME FIRST in this file
// BIND 9.x parses the whole file before using the log
// failure messages up to this point are in (syslog) 
// typically /var/log/messages
//
  logging{
  channel practice_log{
   file "/var/log/named/example.log" versions 3 size 2m;
   severity info;
   print-severity yes;
   print-time yes;
   print-category yes;
 };
 category default{
  practice_log;
 };
};
// required zone for recursive queries
// when building remember to download your root server
zone "." {
  type hint;
  file "root.servers";
};
zone "practicelab.net" in{
  type master;
  file "master/master.example.com";
  // enable slaves only
  allow-transfer {192.168.2.22;192.168.2.24;};
};
// required local host domain
zone "localhost" in{
  type master;
  file "master.localhost";
  allow-update{none;};
};
// localhost reverse map
zone "0.0.127.in-addr.arpa" in{
  type master;
  file "localhost.rev";
  allow-update{none;};
};
// reverse map for class C 192.168.0.0
zone "2.168.192.IN-ADDR.ARPA" in{
  type master;
  file "192.168.0.rev";
};
