// Slave & Cache NAME SERVER for PRACTICELAB.net
// maintained by: me myself alone
// CHANGELOG:
// 1. 17 March 2026 - I created this file 
// This is the configuration file for the slave named server for practicelab.net.
options {
  directory "/var/named";
  // version statement - inhibited for security
  // (avoids hacking any known weaknesses)	
  version "get lost";
  // optional - disables all transfers 
  // notify only from the master server (if enabled) also this will be based on the IP address of the master server
  allow-notify {192.168.2.2;};
  // optional - disables all transfers
  // allow-transfer {none;};
  //close DNS to the world - only allow queries from the local network
  allow-query {
    192.168.2.0/24;
  };
  // optional - disables recursion for everyone except the local network
  allow-recursion {
    192.168.2.0/24;
  };
};
//
// log to /var/log/named/example.log all events from 
// info UP in severity (no debug)
// defaults to use 3 files in rotation
// BIND 8.x logging MUST COME FIRST in this file
// BIND 9.x parses the whole file before using the log
// failure messages up to this point are in (syslog) 
// typically /var/log/messages
//
  logging{
  channel practice_log{
   file "/var/log/named/practice.log" versions 3 size 2m;
   severity info;
   print-severity yes;
   print-time yes;
   print-category yes;
 };
 category default{
  practice_log;
 };
};
// required zone for recursive queries
// when building remember to download your root server
zone "." {
  type hint;
  file "root.servers";
};
zone "practicelab.net" in{
  type slave;
  file "slaves/practicelab.net";
  masters {
    192.168.2.2;
  };
};
// required local host domain
zone "localhost" in{
  type master;
  file "pri.localhost";
  allow-update{none;};
};
// localhost reverse map
zone "0.0.127.in-addr.arpa" in{
  type master;
  file "localhost.rev";
  allow-update{none;};
};
// reverse map for class C 192.168.0.0
zone "2.168.192.IN-ADDR.ARPA" in{
  type slave;
  file "sec.192.168.0.rev";
  masters {
    192.168.2.2;
  };
};
